### ISSUE TITLE
AWS::CloudWatch::Alarm - Drift detection false-positive once adding stack-level tags

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1346]
### Name of the resource

AWS::CloudWatch::Alarm

### Issue Description

Once you create a stack + addings tags on stack-level (!) and your stack containing a `AWS::CloudWatch::Alarm`, the CloudFormation drift detection reporting such stack as drifted (details see "Observed Behavior").

### Expected Behavior

CloudFormation (Drift detection) should be aware that `AWS::CloudWatch::Alarm` doesn't support Tags yet (see also https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/64), hence it's not possible to tag them yet. Furthermore, clarification is needed, if drift detection supports `AWS::CloudWatch::Alarm` - If not, doc needs to be updated and drift detection should return a valid information (like "NOT_SUPPORTED") for this resource.

### Observed Behavior

After adding Stack-Level-Tags to your stack containing a `AWS::CloudWatch::Alarm` and you getting a DRIFTED state for those stacks. This is misleading, since you are not able to fix it. At the same moment other resources inside the stack benefit from setting tags via stack.

### Test Cases

1) Create a new stack with Stack-Level Tags. Here in this example we will add:
```
Environment - dev
ReferenceName - 10902281431
```
![githubAddTagsAlarmStack](https://user-images.githubusercontent.com/16392819/193552037-72fd4e57-7d7c-42ae-8351-b727dfab6f9e.PNG)

2) Using the following simplified CFN YAML template as Stack-Template:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: CFN Drift detection - AWS::CloudWatch::Alarm - Tags are shown as Expected if stack-level-tags are added to the stack - case 10902281431

Resources:
  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: test-alarm if stack has tags
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '90'
      ComparisonOperator: GreaterThanThreshold
```

3) Run CloudFormation Drift detection via "Stack actions" => "Detect drift" in Console
![image](https://user-images.githubusercontent.com/16392819/193081932-7d0a49af-c353-4dff-9387-1d7c99b9c2d5.png)

4) Check the result in the Console. Stack is in state DRIFTED (even there were no changes outside of the stack) - Check the CloudFormation drift detection in Console:
![github-driftDetails](https://user-images.githubusercontent.com/16392819/193552081-7db6633f-a6e2-4307-9b28-3387099de733.PNG)
The Stack-Level-Tags are reported as drift, here Environment + ReferenceName.

### Other Details

* Often a stack contains different resources. It's a Best Practices following the AWS Cloud Development Kit (CDK) to add Tags on Stack-Level as well: https://docs.aws.amazon.com/cdk/v2/guide/tagging.html

**Comment by kanitkah** [comment]
CloudFormation identified an issue with recent release which caused the Drift Detection feature to incorrectly report some resources that do not support tags like CloudWatch::Alarm, AWS::ElasticLoadBalancingV2::Listener, AWS::ElasticLoadBalancingV2::ListenerRule, AWS::Events::Rule etc. as Drifted when stack level tags were applied due to incorrect tag comparison. We are rolling back the deployment and the ETA for finishing the rollback is by 10/14/2022.

**Comment by kanitkah** [comment]
This change has been rolled back.

**Comment by rgoltz** [comment]
Thanks Harshu & Team - This Drift Detection bug/false-positive is resolved. I successfully verified this within our stacks.

**Comment by bertinnv** [comment]
The problem persists in the creation of resources: AWS::ElasticLoadBalancingV2::Listener, AWS::ElasticLoadBalancingV2::ListenerRule, AWS::Events::Rule
