### ISSUE TITLE
AWS::LakeFormation::Permissions DataLocationResource

### ISSUE THREAD

**Issue by BrianFanning** [aws-cloudformation/cloudformation-coverage-roadmap#620]
## 1. AWS::LakeFormation::Permissions DataLocationResource
DataLocationResource is not supported in CloudFormation as per the docs (link in section 5 below)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-permissions-resource.html

Issue #293 also references DataLocationResource and is marked as "Shipped", but it is still not supported

## 6. Category
Analytics

**Comment by Mejato** [comment]
I've tested it and it works. It's just the documentation that's a bit confusing.
Here's the CloudFormation construct:

    "glues3datalocationpermissions": {
      "Type": "AWS::LakeFormation::Permissions",
      "Properties": {
        "DataLakePrincipal": {
          "DataLakePrincipalIdentifier": {
            "Fn::ImportValue": [An identifier for the AWS Lake Formation principal]
          }
        },
        "Resource": {
          "DataLocationResource": {
            "S3Resource": {
              "Fn::ImportValue": [S3 bucket ARN]
            }
          }
        },
        "Permissions": [
          "DATA_LOCATION_ACCESS"
        ]
      }
    } 

And here's the AWS CDK (Python) construct to do the same thing:

    # This Method assigns Lake Formation - Data location permissions to S3
    def assign_data_location_permissions(self, glue_role: iam.Role, s3_bucket: s3.Bucket):
        # Define the CfnPermissions Resource
        s3_data_location_resource = lake.CfnPermissions.DataLocationResourceProperty(s3_resource=s3_bucket.bucket_arn)

        # Define the CfnPermissions Resource Property
        s3_data_location_resource_property = lake.CfnPermissions.ResourceProperty(data_location_resource=s3_data_location_resource)

        # Construct the Glue Role Data Lake Principal property
        glue_data_lake_principle_property = lake.CfnPermissions.DataLakePrincipalProperty(data_lake_principal_identifier=glue_role.role_arn)

        # Define the CfnPermissions
        glue_s3_data_location_permissions = lake.CfnPermissions(self, id='glue_s3_data_location_permissions',
                                                                data_lake_principal=glue_data_lake_principle_property,
                                                                resource=s3_data_location_resource_property,
                                                                permissions=['DATA_LOCATION_ACCESS'])

        return glue_s3_data_location_permissions

**Comment by jaidisido** [comment]
If this is now supported could we please update the AWS CFN [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-permissions-datalocationresource.html) which still show that it's not? It's very confusing for users. Thanks

**Comment by aws-austin-lee** [comment]
Thanks for bringing this to our attention and we apologize for the confusion.  We have updated the docs.

**Comment by hrvining** [comment]
Hello @aws-austin-lee 
Under https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-permissions-datalocationresource.html S3Resource still shows as unsupported. Is there any update on this by chance?

**Comment by dalebradman** [comment]
It's also described as unsupported in the Python API `cdk` docs https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_lakeformation/CfnPermissions.html#datalocationresourceproperty
