### ISSUE TITLE
AWS::RDS::DBCluster - In place upgrade of Aurora DBCluster fails if using custom DBParameterGroup

### ISSUE THREAD

**Issue by pbecotte** [aws-cloudformation/cloudformation-coverage-roadmap#896]
As referenced -

_Originally posted by @saiya in https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/216#issuecomment-754628106_

The new upgrade functionality doesn't work if you have a custom DBParameter group, because for version upgrades the RDS api expects you to pass a new --db-intance-parameter-group in the `modify_cluster` api call. We replace the parameter group on the instances themselves, but this api call is still failing.

We've tried a couple workarounds to try to get the upgrade to be an entirely CFN based process, but haven't figured anything out yet. Just wanted to ensure this is tracked.

**Comment by gitcdb** [comment]
Won't be a shock to you given the topic, but yeah this is the error that gets dumped out for anyone that runs into a similar situation. 

You must explicitly specify a new DB instance parameter group, either default or custom, for the engine version upgrade. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; 

I've employed a Blue/Green solution as per Mike N's solution here https://stackoverflow.com/questions/68086201/how-to-do-a-major-version-upgrade-for-aurora-postgres-in-cloudformation-with-cus but unfortunately while the default DBClusterParmeterGroup and DBParameterGroup Green and Blue are created and used by the cluster and db instances respectively, when shifting to a green (or likewise I guess a blue if you're already green) CFN looks to delete whatever flagged group you specify to replace it with in my case a postgresql13 family version, and thus runs into the problem. 

Annoying that.

**Comment by dbayardAWS** [comment]
As noted in the original comment, the CLI/API for DBCluster has a new --db-intance-parameter-group in the modify_cluster api call that lets the CLI/API do a major version upgrade in a single step in the scenario where you use custom Instance parameter groups.  The enhancement request is to see if similar capabilities can be exposed in CFN so that you don't need to do the 2 step update anymore.

**Comment by osdrv** [comment]
The issue was fixed by https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/311 and is not globally available. Please refer to the [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-dbinstanceparametergroupname) for more details. The ticket might be closed now.

**Comment by sushdesh** [comment]
Still facing same issue when upgrading with custom instance parameter group (custom or default parameter group works fine).

**Comment by sushdesh** [comment]
related #1373 ?

**Comment by tadhglewis** [comment]
Bump - also running into the same issue when upgrading postgres and the custom instance parameter group

**Comment by sushdesh** [comment]
> Bump - also running into the same issue when upgrading postgres and the custom instance parameter group

@tadhglewis can you try adding DBParameterGroupName parameter at both Instance and Cluster resource levels and upgrading? 

(If its a regional Aurora cluster, upgrade goes fine)

**Comment by tadhglewis** [comment]
@sushdesh that works... definitely didn't waste a stupid amount of time trying to debug this...

For context we had a default `DBClusterParameterGroupName` on the cluster and on each instance we had a custom `DBParameterGroupName`.

Simply adding `DBInstanceParameterGroupName` to the cluster fixed the issue :/

**Comment by RemyNtshaykolo** [comment]
Using aws cli instead of `--target-db-parameter-group-name` option, use`--target-db-cluster-parameter-group-name`
